// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzTTR2OJDXEDBsXf0uG91rCLLlvrxs5MU',
    appId: '1:705513528770:web:0170a7877e79b7521e0a5b',
    messagingSenderId: '705513528770',
    projectId: 'trendtribe-ecommerce',
    authDomain: 'trendtribe-ecommerce.firebaseapp.com',
    storageBucket: 'trendtribe-ecommerce.firebasestorage.app',
    measurementId: 'G-B7ZCC3QC87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtORA3kztSk9wxueNqBSXYBShQLx2w3go',
    appId: '1:705513528770:android:d01f4b81c4f6f0701e0a5b',
    messagingSenderId: '705513528770',
    projectId: 'trendtribe-ecommerce',
    storageBucket: 'trendtribe-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy04QHM89YGif_22rb5HshwKoqMKpE154',
    appId: '1:705513528770:ios:570ac0f3238a8f091e0a5b',
    messagingSenderId: '705513528770',
    projectId: 'trendtribe-ecommerce',
    storageBucket: 'trendtribe-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.trandtribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy04QHM89YGif_22rb5HshwKoqMKpE154',
    appId: '1:705513528770:ios:570ac0f3238a8f091e0a5b',
    messagingSenderId: '705513528770',
    projectId: 'trendtribe-ecommerce',
    storageBucket: 'trendtribe-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.trandtribe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzTTR2OJDXEDBsXf0uG91rCLLlvrxs5MU',
    appId: '1:705513528770:web:fa60a179f2e396321e0a5b',
    messagingSenderId: '705513528770',
    projectId: 'trendtribe-ecommerce',
    authDomain: 'trendtribe-ecommerce.firebaseapp.com',
    storageBucket: 'trendtribe-ecommerce.firebasestorage.app',
    measurementId: 'G-YTY3T252NY',
  );
}
